check_timer_period: 20000

actions:
  EXTEND_OVERWORLD_BARRIER_100: "Расширение границ верхнего мира на 100 блоков"
  EXTEND_OVERWORLD_BARRIER_300: "Расширение границ верхнего мира на 300 блоков"
  EXTEND_OVERWORLD_BARRIER_500: "Расширение границ верхнего мира на 500 блоков"
  EXTEND_OVERWORLD_BARRIER_1000: "Расширение границ верхнего мира на 1000 блоков"
  EXTEND_NETHER_BARRIER_100: "Расширение границ нижнего мира на 100 блоков"
  EXTEND_NETHER_BARRIER_300: "Расширение границ нижнего мира на 300 блоков"
  EXTEND_NETHER_BARRIER_500: "Расширение границ нижнего мира на 500 блоков"
  EXTEND_NETHER_BARRIER_1000: "Расширение границ нижнего мира на 1000 блоков"
  EXTEND_END_BARRIER_100: "Расширение границ мира края на 100 блоков"
  EXTEND_END_BARRIER_300: "Расширение границ мира края на 300 блоков"
  EXTEND_END_BARRIER_500: "Расширение границ мира края на 500 блоков"
  EXTEND_END_BARRIER_1000: "Расширение границ мира края на 1000 блоков"
  ADMIN_LIGHTNING_BOLT: "Ударить администратора An1by молнией"

messages:
  not_enough_aura: "<red>У вас недостаточно ауры!"
  database_error: "<red>Ошибка базы! Свяжитесь с администратором!"

  invalid_aura: "<red>Указано недоступное количество ауры!"

  collection_exists: "<red>Сбор на уже запущен! (<yellow><action_name></yellow>)"
  collection_not_exists: "<red>Активный сбор не найден!"
  collection_create: "<gold><admin> запустил сбор на <yellow><action_name><gold>!\n<click:suggest_command:/collection deposit >Вложить ауру</click>"
  collection_create_command: "<greem>Вы успешно запустили сбор!"
  collection_end_force: "<yellow>Сбор был досрочно завершен (<admin>)"
  collection_end_success: "<yellow>Сбор на <action_name> успешно закончен!\n<green>Производим действие..."
  collection_end_fail: "<yellow>Сбор на <action_name> закончен! Собрано ауры: <collected_aura>/<collection_cost>\n<red>Действие не будет выполнено!"
  collection_deposit: "<green>Вы успешно вложили <deposit_aura> ауры в сбор на <yellow><action_name></yellow>!\nСобрано: <yellow><collected_aura>/<collection_cost>"
  collection_deposit_return: "<yellow>Вам было возвращено <gold><deposit_return_aura> ауры</gold> за сбор <action_name>"

  vote_exists: "<red>Опрос уже запущен!"
  vote_not_exists: "<red>Активный опрос не найден!"
  vote_start_header: "<gold><admin> запускает новый опрос!\n"
  vote_start_button_format: "<yellow><click:run_command:/vote answer %answer%>%answer%</click></yellow>"
  vote_start_button_delimiter: "<white> | </white>"
  vote_create_command: "<greem>Вы успешно запустили опрос!"
  vote_end_header: "<gold>Опрос заверешн! Результат опроса: <yellow><vote_result>\n<gold>Голоса:"
  vote_end_answer_format: "<gold>*</gold> <yellow><answer> - <answer_frequency></yellow>"
  vote_end_answer_delimiter: "\n"
  vote_end_force: "<yellow>Опрос был досрочно завершен (<admin>)"
  vote_answer: "<green>Вы проголосовали в опросе: <answer>"
  vote_already_voted: "<red>Вы уже проголосовали в опросе!"
  vote_invalid_answer: "<red>Неизвестный ответ на опрос!"
  vote_no_possible_answers: "<red>Отсутствуют возможные ответы!"
  vote_result_not_certain: "неопределен"
  vote_answers_set: "<green>Возможные ответы для опроса установлены!"
  vote_start: "<green>Опрос успешно запущен!"