list:
  messages_per_page: 10

messages:
  invalid_executor: "<red>Неверный исполнитель!"
  highlighted: "<green>Вы подсветили для себя игрока <target>"
  highlighting_disabled: "<green>Вы убрали подсветку с <target>"

  visibility_hide: "<green>Вы скрылись от <target>!"
  visibility_show: "<green>Вы показались <target>!"

  invalid_arguments: "<red>Указаны неверные аргументы!"
  no_event: "<red>Ивент не найден!"
  answer_accepted: "<green>Вы приняли ивент от гейм-мастера! Потрачено ауры: <event_aura>"
  answer_declined: "<yellow>Вы отклонили ивент от гейм-мастера!"
  answer_response: "<green><click:run_command:/event answer accept>Принять</click></green> / <red><click:run_command:/event answer decline>Отклонить</click></red>"
  list_title: "<yellow>Сообщения игрока <name>"
  list_prefix: "<yellow><date> <sender>: "